config/routes.rb
Rails.application.routes.draw do
  resources :kittens

  root 'kittens#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, length: {in: 3..255}
  validates :age, numericality: {only_integer: true,
    greater_than: 0}
  validates :cuteness, numericality: {only_integer: true,
    greater_than: 0}
  validates :softness, numericality: {only_integer: true,
    greater_than: 0}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :get_kitten, only: [:show, :edit, :update]
  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = 'Kitten Created!'
      redirect_to @kitten
    else
      flash.now[:warning] = 'How hard is it to create a kitten??'
      render 'new'
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json {render json: @kitten}
    end
  end

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json {render json: @kittens}
    end
  end

  def edit

  end

  def update
    @kitten.update_attributes(kitten_params)
    flash[:success] = 'Kitten updated'
    redirect_to @kitten
  end

  def destroy
    Kitten.find(params[:id]).destroy
    flash[:success] = 'Kitten deleted'
    redirect_to kittens_path
  end

  private

  def get_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitten_params
    params.require(:kitten).permit(:name,:age,:cuteness,:softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= render partial: 'shared/errors', locals: {object: @kitten }%>
<%= form_for @kitten do |f| %>
<%= f.label :name, 'Name:' %>
<%= f.text_field :name, class: 'form-control'%> <br>
<%= f.label :age, 'Age in weeks:' %>
<%= f.number_field :age, class: 'form-control' %> <br>
<%= f.label :cuteness, 'Cuteness 1-10' %>
<%= f.select :cuteness, options_for_select((1..10).to_a),
  class: 'form-control' %>
<%= f.label :softness, 'Softness 1-10' %>
<%= f.select :softness, options_for_select((1..10).to_a,1),
    class: 'form-control' %> <br>
<%= f.submit kitten_action %>
<% end %>

app/views/kittens/_kitten.html.erb
<%= link_to "Kitten: #{kitten.name}", kitten %>
<%= link_to 'Edit', edit_kitten_path(kitten) %>
<%= link_to 'Delete', kitten_path(kitten), method: :delete %>
<br>

app/views/kittens/edit.html.erb
<h1>Edit this kitten</h1>
<%= render 'form', kitten_action: 'Update' %>

app/views/kittens/index.html.erb
<h1>All these Kittens</h1>
<%= render @kittens %>
<br>
<%= link_to 'Create a new kitten!', new_kitten_path %>

app/views/kittens/new.html.erb
<h1>Create a Kitten!</h1>
<%= render 'form' , kitten_action: 'Create a Kitten'%>

app/views/kittens/show.html.erb
<h1>About this kitten</h1>
Kitten: <%= @kitten.name %>  <br>
Age: <%= pluralize(@kitten.age,'week' )  %> old <br>
Softness: <%= @kitten.softness %>/10 | Cuteness: <%= @kitten.cuteness %>/10 <br>
<%= link_to 'Edit', edit_kitten_path(@kitten) %> |
<%= link_to 'Delete', kitten_path(@kitten), method: 'delete' %> |
<%= link_to 'All Kittens', kittens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
          <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
          <% end %>
          <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    This form contains <%= pluralize(object.errors.count, 'errors')%>:
    <ul>
    <% object.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  </div>
<% end %>